name: Build Debian SVITE image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-debian-svite.yaml
      - gitea-runner/Dockerfile

env:
  CONTAINER_REGISTRY: ghcr.io
  DEBIAN_SNAPSHOT: bullseye-20220328

jobs:
  build-debian-svite:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}
          tags: |
            ${{ env.DEBIAN_SNAPSHOT }}
            type=raw,value=${{ env.DEBIAN_SNAPSHOT }}-{{sha}}
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}

      - name: Login to image registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ## Build the image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: gitea-runner
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          build-args: |
            DEBIAN_SNAPSHOT=${{ env.DEBIAN_SNAPSHOT }}
            TZ=${{ vars.TZ || 'Europe/Berlin' }}
